PROGRAM CONVERT1;
VAR
  F: INTEGER;
  C: INTEGER;
BEGIN
  READ (F) ;
  IF F < 100 THEN
    BEGIN
  	  WRITE('TEMP IS TOO LOW!');
	    WRITE('IS IT REALLY THAT COLD?')
    END
  ELSE
    BEGIN
      C := (F-32)*(5/9);
      WRITE (' FAHRENHEIT = ');
      WRITE (F);
      WRITE (' CELSIUS= ');
      WRITE (C)
    END
END
